Implement binary protocol between client and server
micronaut-projects/micronaut-test-resources pull request #297
Opened 2023-05-30 09:18 UTC by melix

This commit introduces a custom protocol for communicating between the client and the server. Instead of using JSON, it now uses a binary protocol. This removes the requirement of having Micronaut JSON on the user classpath (on the client side) and further reduces the number of dependencies of the server.

This is a major breaking change, and it's no longer possible to directly use tools like cURL or httpie to talk to the server.

This is blocked by https://github.com/micronaut-projects/micronaut-core/issues/9331

2023-05-30 10:02 UTC, melix commented
Sonar analysis seems completely off.

2023-05-30 12:49 UTC, graemerocher requested changes

2023-05-30 14:21 UTC, graemerocher approved these changes

2026-04-28 22:05 UTC, alvarosanchez commented
Superseded by #1052

2026-04-28 22:05 UTC, closed without merging