Add support for mysql-connector-j
micronaut-projects/micronaut-test-resources pull request #409
Opened 2023-10-03 13:06 UTC by radovanradic

Support added for mysql-connector-j besides already supported mysql-connector-java, needed for micronaut-sql and starter

2023-10-03 13:15 UTC, sdelamo requested changes
should not we keep both `mysql-connector-java` and `mysql-connnector-j`?

2023-10-03 13:17 UTC, radovanradic commented
> should not we keep both `mysql-connector-java` and `mysql-connnector-j`?

Yes and we do, just added `mysql-connector-j` to the list with already existing `mysql-connector-java`. Can be seen in tests as well.

2023-10-03 13:18 UTC, melix approved these changes

2023-10-03 13:36 UTC, wetted approved these changes

2023-10-04 07:00 UTC, radovanradic commented on test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java
> +            m.onArtifact(name -> name.startsWith(MICRONAUT_DATA_PREFIX), deps -> deps.anyMatch(d -> MYSQL_DRIVERS.contains(d.getModule())), MYSQL_MODULE);
Matching against all of the MySQL supported libs in the list defined above

2023-10-04 07:01 UTC, radovanradic commented on test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java
> +                MYSQL_MYSQL_CONNECTOR_JAVA, MYSQL_MYSQL_CONNECTOR_J,
Both connector and connector-j supplied, so both are supported

2023-10-05 07:19 UTC, merged