Update modules-control-panel.adoc
micronaut-projects/micronaut-test-resources pull request #476
Opened 2023-12-12 05:14 UTC by ZacharyKlein

Indicate how to add the control panel module

2023-12-12 08:32 UTC, melix requested changes
Thanks for the suggestion. I would however prefer that we have an intro explaining what this snippet is about. In particular, we don't document the integration with Gradle or Maven plugins in that doc.

A couple suggestions:

- either add a link to the Gradle/Maven plugins doc, e.g this section: https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#_configuring_the_test_resources_plugin and explain that the `control-panel` module has to be added
- or explain for both plugins how to do it

Ideally, for the Gradle snippets, you should use `KnownModules.CONTROL_PANEL`, not the string.

2024-02-02 10:24 UTC, sdelamo commented
@alvarosanchez @melix should should add this to starter when someone adds `control-panel` feature? https://github.com/micronaut-projects/micronaut-test-resources/pull/476/files

2024-02-02 10:26 UTC, melix commented
That's the control panel for the test resources module itself. So you could use the control panel in test resources without using control panel in your own app and vice-versa. Maybe the easiest is actually to include the control panel by default in starter when test resources are enabled, it's useful anyway.

2024-02-02 10:26 UTC, alvarosanchez commented
> include the control panel by default in starter when test resources are enabled

This is what I agree with

2024-02-07 21:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-test-resources?pullRequest=476) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-test-resources?pullRequest=476) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-test-resources?pullRequest=476) it.</sub>

2026-04-24 09:05 UTC, closed without merging