add minio support
micronaut-projects/micronaut-test-resources pull request #670
Opened 2024-07-21 00:02 UTC by brucemelo

add minio support - testcontainers

2024-07-22 09:10 UTC, melix requested changes
Many thanks for the contribution! Would you mind also adding the corresponding docs in `src/main/docs/guide`?

2024-07-22 12:54 UTC, brucemelo commented
> Many thanks for the contribution! Would you mind also adding the corresponding docs in `src/main/docs/guide`?

Thanks for the feedback. The docs have been added.

2024-07-22 13:24 UTC, melix approved these changes

2026-04-22 21:18 UTC, alvarosanchez requested changes
Requested changes.

2026-04-23 12:04 UTC, alvarosanchez commented
Superseded by #1048

2026-04-23 12:04 UTC, closed without merging